In [1]:
import numpy as np

Numpy main purpose is homogeneous multidimensional array

There's also python arrays (array.array), but they're only 1 dimensional and not nearly as good

Making arrays - from list

In [7]:
A1D = np.array([1,2,3,4])
A2D = np.array([[1,2], [3,4]])
A3D = np.array([[[1,2], [3,4]], [[5,6], [7,8]]])

In [6]:
A1D.dtype

dtype('float64')

In [8]:
A2D

array([[1, 2],
       [3, 4]])

In [9]:
A3D

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [10]:
A2D.ndim # number of axis

2

In [11]:
A2D.size # total number of elements

4

In [12]:
A2D.shape # dimensions of array (as a tuple - n rows x m columns)

(2, 2)

In [13]:
A2D.dtype

dtype('int32')

In [14]:
A3D.size

8

### Generate array

In [16]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [19]:
np.arange(10, 1, -1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2])

In [16]:
np.linspace(1,100,10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [17]:
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [18]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [19]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [20]:
np.ones((2,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [26]:
ofloat=np.ones(10, dtype = int)

In [27]:
ofloat

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [28]:
ofloat.dtype

dtype('int32')

In [29]:
print(A1D)

[1 2 3 4]


In [30]:
b2D = np.arange(12).reshape(4, 3) 

In [31]:
print(b2D)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


# Basic Operations

In [20]:
# Standard arithmetic

In [21]:
a= np.array([20, 30, 40, 50])
b= np.arange(4)

In [23]:
a-b

array([20, 29, 38, 47])

In [24]:
b**2

array([0, 1, 4, 9], dtype=int32)

In [25]:
10 * np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [26]:
a < 35

array([ True,  True, False, False])

In [27]:
A = np.array([[1, 1],
              [0, 1]])

In [28]:
B = np.array([[2, 0],
              [3, 4]])

In [29]:
A * B #elementwise product

array([[2, 0],
       [0, 4]])

In [42]:
A @ B #matrix product

array([[5, 4],
       [3, 4]])

In [45]:
#other functions

In [40]:
rg = np.random.default_rng(1)

In [41]:
a = rg.random((2, 3))

In [48]:
a

array([[0.51182162, 0.9504637 , 0.14415961],
       [0.94864945, 0.31183145, 0.42332645]])

In [49]:
a.sum() #sum of all elements

3.290252281866131

In [51]:
a.min() #min of all elements

0.14415961271963373

In [52]:
a.sum(axis=0) 

array([1.46047107, 1.26229515, 0.56748606])

In [53]:
a.sum(axis=1)

array([1.60644493, 1.68380735])

### indexing, slicing, iterating

One-dimensional arrays can be indexed, sliced and iterated over just like lists

In [30]:
a = np.arange(10)**3

In [32]:
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [33]:
a[2]

8

In [34]:
a[2:5]

array([ 8, 27, 64], dtype=int32)

In [35]:
a[:6:2] = 1000

In [36]:
a

array([1000,    1, 1000,   27, 1000,  125,  216,  343,  512,  729],
      dtype=int32)

In [37]:
a[::-1]

array([ 729,  512,  343,  216,  125, 1000,   27, 1000,    1, 1000],
      dtype=int32)

In [38]:
for i in a:
    print(i**(1 / 3.))

9.999999999999998
1.0
9.999999999999998
3.0
9.999999999999998
5.0
5.999999999999999
6.999999999999999
7.999999999999999
8.999999999999998


### changing the shape of an array

In [46]:
rg.random((3, 4))

array([[0.20345524, 0.26231334, 0.75036467, 0.28040876],
       [0.48519097, 0.9807372 , 0.96165719, 0.72478994],
       [0.54122686, 0.2768912 , 0.16065201, 0.96992541]])

In [42]:
a=np.floor(10 * rg.random((3, 4)))

In [43]:
a

array([[8., 4., 5., 0.],
       [7., 5., 3., 7.],
       [3., 4., 1., 4.]])

In [47]:
a.shape

(3, 4)

In [48]:
a.ravel() #flatten array

array([8., 4., 5., 0., 7., 5., 3., 7., 3., 4., 1., 4.])

In [49]:
a.reshape(6, 2)

array([[8., 4.],
       [5., 0.],
       [7., 5.],
       [3., 7.],
       [3., 4.],
       [1., 4.]])

In [50]:
a.T #transpose

array([[8., 7., 3.],
       [4., 5., 4.],
       [5., 3., 1.],
       [0., 7., 4.]])

### stacking arrays

arrays can be stacked together along different axes

In [54]:
a = np.floor(10 * rg.random((2, 2)))

In [55]:
b = np.floor(10 * rg.random((2, 2)))

In [56]:
a

array([[4., 0.],
       [6., 8.]])

In [57]:
b

array([[5., 2.],
       [8., 5.]])

In [58]:
np.vstack((a, b))

array([[4., 0.],
       [6., 8.],
       [5., 2.],
       [8., 5.]])

In [59]:
np.hstack((a, b))

array([[4., 0., 5., 2.],
       [6., 8., 8., 5.]])

### indexing with boolean arrays

In [60]:
a = np.arange(12).reshape(3, 4)

In [61]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [62]:
a>4

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [63]:
b = a > 4

In [64]:
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [65]:
a[b]

array([ 5,  6,  7,  8,  9, 10, 11])

In [67]:
b1 = np.array([False, True, True])  
b2 = np.array([True, False, True, False]) 

In [68]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [69]:
a[b1,b2] #filter on rows

array([ 4, 10])

In [90]:
a[:, b2]  #filter on columns

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

### vectorization

Numpy arrays are homogenous, unlike lists. Vectorization takes advantage of this - doesnt have to 'loop' through elements

In [70]:
%%time
np.sum(np.arange(100000))

CPU times: total: 0 ns
Wall time: 755 µs


704982704

In [72]:
import time

In [76]:
time.time()

1674024368.4027307

In [77]:
%%time
sum(list(np.arange(100000)))

CPU times: total: 15.6 ms
Wall time: 23.8 ms


<timed eval>:1: RuntimeWarning: overflow encountered in long_scalars


704982704

In [78]:
%%time
total = 0
for i in np.arange(100000):
    total = i + total
total

CPU times: total: 62.5 ms
Wall time: 50 ms


<timed exec>:3: RuntimeWarning: overflow encountered in long_scalars


704982704

Can also use broadcasting (essentially extrapolating an array to match as required)

real example from seacalcs wt calc:

In [79]:
def gamma_p(beta, p_i, p_e, p_b):
    """
    Parameter accouting for effect of D/t2 ratio as per DNVGL-ST-F101 December 2017 Eq.5.23
    :param beta:[-] Factor used in combined loading criteria
    :param p_i:[Pa] Internal pressure
    :param p_e:[Pa] External pressure
    :param p_b:[Pa] Burst pressure
    :return:[-] gamma_p
    """
    if (p_i - p_e) / p_b <= 2 / 3:
        return 1 - beta

    elif (p_i - p_e) / p_b > 2 / 3:
        return 1 - 3 * beta * (1 - (p_i - p_e) / p_b)

In [81]:
gamma_p(0.2, np.arange(10000, 1000000, 100), 100000, 100000)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [ ]:
for x in np.arange(10000, 1000000, 100)

In [82]:
@np.vectorize
def gamma_p(beta, p_i, p_e, p_b):
    """
    Parameter accouting for effect of D/t2 ratio as per DNVGL-ST-F101 December 2017 Eq.5.23
    :param beta:[-] Factor used in combined loading criteria
    :param p_i:[Pa] Internal pressure
    :param p_e:[Pa] External pressure
    :param p_b:[Pa] Burst pressure
    :return:[-] gamma_p
    """
    if (p_i - p_e) / p_b <= 2 / 3:
        return 1 - beta

    elif (p_i - p_e) / p_b > 2 / 3:
        return 1 - 3 * beta * (1 - (p_i - p_e) / p_b)

In [83]:
gamma_p(0.2, np.arange(10000, 1000000, 100), 100000, 100000)

array([0.8   , 0.8   , 0.8   , ..., 5.7982, 5.7988, 5.7994])